server:
  port: 8761

spring:
  application:
    name: discovery-server
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    status-page-url-path: /info
    health-check-url-path: /health
  server:
    peerEurekaNodesUpdateIntervalMs: 60000
    enableSelfPreservation: true
  client:
    healthcheck:
      enabled: true
    eurekaServiceUrlPollIntervalSeconds: 60
    fetch-registry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/