server:
  port: 5202
spring:
  application:
    name: app-producer
  cloud:
    nacos:
      discovery:
        server-addr: 120.48.86.143:8848

dubbo:
  application:
    name: dubbo-producer
  registry:
    address: nacos://120.48.86.143:8848
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.umbrella
