package com.umbrella.demo.config;

public interface Constants {
    String MQ_TEST_TOPIC = "Bull-Small-Trumpet-Topic";

    String BULL_DAILY_LATEST_ORDER_ONE_HOUR_KEY = "BULL:DAILY:LATEST:ORDER_ONE_HOUR:";
    String BULL_DAILY_LATEST_ORDER_SIX_HOUR_KEY = "BULL:DAILY:LATEST:ORDER_SIX_HOUR:";
    String BULL_DAILY_PRICE_KEY = "BULL:DAILY:PRICE:";
    String BULL_DAILY_LATEST_PRICE_KEY = "BULL:DAILY:LATEST:PRICE:";
    String BULL_DAILY_CURRENT_PRICE_KEY = "BULL:DAILY:CURRENT:PRICE:";
}
