server:
  port: 4001
spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://120.48.86.143:3306/um_customer?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
          username: root
          password: Doalso@2311#$9
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://120.48.86.143:3306/um_customer_slave?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
          username: root
          password: Doalso@2311#$9
          driver-class-name: com.mysql.cj.jdbc.Driver

  elasticsearch:
    uris: https://120.48.86.143:9200
    username: elastic
    password: N4cTe-C-OtslAeAYaZMg

  data:
    mongodb:
      uri: mongodb://120.48.86.143:27017/test
    redis:
      host: localhost
      database: 0

rocketmq:
  name-server: 120.48.86.143:9876
  producer:
    group: Umbrella-Producer-Group
    #消息发送的超时时间 默认3000ms
    send-message-timeout: 3000
    #消息达到4096字节的时候，消息就会被压缩。默认 4096
    compress-message-body-threshold: 4096
    #最大的消息限制，默认为128K
    max-message-size: 4194304
    #同步消息发送失败重试次数
    retry-times-when-send-failed: 3
    #在内部发送失败时是否重试其他代理，这个参数在有多个broker时才生效
    retry-next-server: true
    #异步消息发送失败重试的次数
    retry-times-when-send-async-failed: 3

justauth:
  enabled: true
  cache:
    type: redis
  extend:
    enum-class: com.umbrella.justauth.support.extend.ExtendSource
    config:
      HUIONE:
        request-class: com.umbrella.justauth.support.extend.ExtendHuioneRequest
        client-id: 243r4343
        client-secret: 243red34342
        redirect-uri: https://oauth.chatme.com/oauth/huione/callback
  type:
    GOOGLE:
      client-id: 124834461273-qse1cno6tkttqjb4pk1pe3lsivhvs8go.apps.googleusercontent.com
      client-secret: 124834461273-qse1cno6tkttqjb4pk1pe3lsivhvs8go.apps.googleusercontent.com
      redirect-uri: http://localhost:4001/oauth/GOOGLE/callback
    FACEBOOK:
      client-id: 243r4343
      client-secret: 243red34342
      redirect-uri: https://oauth.chatme.com/oauth/facebook/callback
    TWITTER:
      client-id: 243r4343
      client-secret: 243red34342
      redirect-uri: https://oauth.chatme.com/oauth/twitter/callback
